### ISSUE TITLE
Accommodation for multiple python version

### ISSUE THREAD

**Issue by Neelaksh-Singh** [mammuth/bitcoin-arbitrage-trading-bot#47]
I was trying to setup the monitor locally when I ran into the issue of pipenv not accepting python version greater than 3.6 .
On further research, I found a similar issue raised [here](https://github.com/pypa/pipenv/issues/1050). This was indeed related to the Pipfile configuration.
I would be happy to resolve it.

**Comment by mammuth** [comment]
The easiest fix, for now, might be to run it inside a Docker container that uses the python version the Pipfile expects.

If we can improve compatibility by updating the Pipfile accordingly, feel free to do so!

**Comment by mammuth** [comment]
closed via https://github.com/mammuth/bitcoin-arbitrage-trading-bot/pull/48
Thanks!
